# coding: utf8
TAGS = {
        "magento" : ["magento", "magneto"],
        "opencart" : ["opencart"],
        "prestashop" : ["prestashop"],
        "woocommerce" : ["wordpress", "woocommerce"],
        "vtex" : ["vtex"],
        "iset" : ["iset"],
        "betalabs" : ["betalabs", "beta labs"],
        "bis2bis" : ["bis2bis"],
        "ezcommerce" : ["ezcommerce", "ez commerce"],
        "lojaintegrada" : ["lojaintegrada", "loja integrada"],
        "dotstore" : ["dotstore", "dot store"],
        "fitcommerce" : ["fitcommerce", "fit commerce"],
        "signativa" : ["signativa"],
        "flexy" : ["flexy" ],
        "egondola" : ["egondola", "e gondola" ],
        "showare" : ["showare"],
        "edools": ["edools", "e dools", "e-dools"],
        "fbits": ["fbits", "fibits", "f-bits", "fi-bits"],
        "mkxwebsite": ["mkx", "mkxwebsite", "mkx website"],
        "bubb": ["bubb"],
        "e-com.club": ["ecom.club", "e-com.club"],
        "lojcomm": ["lojcomm", "lojconn", "lojcom", "lojcon"],
        "uoou": ["uoou"],
        "internetAd": ["internetad"],
        "dlojavirtual": ["dlojavirtual", "dloja virtual"],
        "jetcommerce": ["jetcommerce", "jetcomerce", "jet commerce", "jet comerce"],
        "2mind": ["2mind", "2 mind"],
        "bizcommerce": ["bizcommerce", "bizcomerce", "biz commerce", "biz comerce"],
        "php": ["php", "phpv2", "phpv3", "v2", "v3", "php v2", "php v3"],
        "java": ["java"],
        "c#": ["c#", ".net", "aspnet", "vb", "vb.net", "asp.net", "csharp", "visual basic", "visualbasic"],
        "ruby": ["ruby", "rails"],
        "python": ["python", "pithon", "pyton", "piton"],
        "javascript": ["javascript", "js", "pagarme-js", "node", "nodejs", "node.js"],
        "react": ["react", "reactjs"],
        "angular": ["angular", "angularjs"],
        "curl": ["curl"],
        "api": ["api"],
        "reindexação": ["desapareceu", "desapareceram", "sumiu", "sumiram"],
        "elasticsearch": ["elasticsearch", "elastic search"],
        "marketplace": ["marketplace", "market place", "mktplace", "mkt place", "split", "split_rule", "split_rules", "split rules", "split"],
        "assinatura": ["plans", "plan", "subscription", "subscriptions", "assinatura", "assinaturas", "planos", "plano", "recorrencia"],
        "transação": ["transação", "transaction", "transacao"],
        "timeout": ["timeout", "time out"],
        "checkout": ["checkout", "checkout pagar.me"],
        "transferência": ["transferencia", "transfer", "tranferencia", "trasferencia", "transfers"],
        "saque": ["saque", "saques", "transfers"],
        "antecipação": ["anticipation", "bulk_anticipation", "antecipacao", "antecipar", "antecipa", "anticipa"],
        "dashboard": ["dash", "dashboard", "board"],
        "postback": ["postback", "hookshot", "notificacao", "notificacoes"],
        "do_nada": ["funcionar", "parou", "parou de funcionar", "nao mexi"],
        "mundo_físico": ["maquininha", "android", "ios", "emv", "magstripe", "pos", "mpos", "pinpad"],
        "saldo": ["saldo", "balance"],
        "boleto": ["boleto", "boleto bancario", "bancario"],
        "cartão_de_crédito": ["credit_card", "cartao de credito", "credit", "card"],
        "cartão_de_débito": ["debit_card", "debito", "cartao de debito", "debit"],
        "card_hash": ["card_hash", "hash"],
        "cobrança": ["cobranca"],
        "cliente": ["customer", "cliente"],
        "estorno": ["estorno", "refund", "refunded"],
        "reprocessar": ["reprocessar", "reprocessar"],
        "conta_bancária": ["bank_account", "bank account", "conta bancaria", "bancaria"],
        "antifraude": ["antifraud", "antifraude", "clearsale", "konduto"]
        }
