# coding: utf8
TAGS = { "magento" : ["magento", "magneto"],
        "opencart" : ["opencart"],
        "prestashop" : ["prestashop"],
        "woocommerce" : ["wordpress, woocommerce"],
        "vtex" : ["vtex"],
        "iset" : ["iset"],
        "betalabs" : ["betalabs", "beta labs"],
        "bis2bis" : ["bis2bis"],
        "ezcommerce" : ["ezcommerce", "ez commerce"],
        "lojaintegrada" : ["lojaintegrada, loja integrada"],
        "dotstore" : ["dotstore, dot store"],
        "fitcommerce" : ["fitcommerce, fit commerce"],
        "signativa" : ["signativa"],
        "flexy" : ["flexy", "flex"],
        "egondola" : ["egondola", "e gondola", "e-dools"],
        "showare" : ["showare"],
        "edools": ["edools", "e dools", "e-dools"],
        "fbits": ["fbits", "fibits", "f-bits", "fi-bits"],
        "mkxwebsite": ["mkx", "mkxwebsite", "mkx website"],
        "bubb": ["bubb"],
        "e-com.club": ["e-com", "ecom", "ecomclub", "ecom.club", "e-com.club"],
        "lojcomm": ["lojcomm", "lojconn", "lojcom", "lojcon"],
        "uoou": ["uoou", "uou"],
        "internetAd": ["internetad"],
        "dlojavirtual": ["dloja", "dlojavirtual", "dloja virtual"],
        "oxigenio": ["oxigenio"],
        "jetcommerce": ["jetcommerce", "jetcomerce", "jet commerce", "jet comerce"],
        "core": ["core"],
        "2mind": ["2mind", "2 mind"],
        "bizcommerce": ["bizcommerce", "bizcomerce", "biz commerce", "biz comerce"],
        "php": ["php", "phpv2", "phpv3", "v2", "v3", "php v2", "php v3"],
        "java": ["java"],
        "c#": ["c#", ".net", "aspnet", "vb", "vb.net", "asp.net", "csharp", "visual basic", "visualbasic", "cs"],
        "ruby": ["ruby", "rails", "rb"],
        "python": ["python", "py", "pithon", "pyton", "piton"],
        "curl": ["curl"],
        "api": ["api"],
        "elasticsearch": ["elasticsearch", "elastic search"], 
        "marketplace": ["marketplace", "market place", "mktplace", "mkt place", "split", "split_rule", "split_rules", "split rules", "split"],
        "assinatura": ["plans", "plan", "subscription", "subscriptions", "assinatura", "assinaturas", "planos", "plano"],
        "transação": ["transação", "transaction", "transacao"],
        "timeout": ["timeout", "time out"],
        "checkout": ["checkout", "checkout pagar.me"],
        "transferência": ["transferencia", "transfer", "tranferencia", "trasferencia", "transfers"],
        "saque": ["saque", "saques", "transfers"],
        "antecipação": ["anticipation", "bulk_anticipation", "antecipação", "antecipar", "antecipa", "anticipa"],
        "dashboard": ["dash", "dashboard", "board"],
        "postback": ["postback", "post", "back"],
        "do nada": ["funcionar", "parou", "parou de funcionar", "nao mexi"],
        "mundo físico": ["maquininha", "android", "ios", "emv", "magstripe"],
        "saldo": ["saldo", "balance"],
        "boleto": ["boleto", "boleto bancário", "bancário"],
        "cartão de crédito": ["credit_card", "cartao de credito", "credit", "card"],
        "cartão de débito": ["debit_card", "debito", "cartao de debito", "debit"],
        "card_hash": ["card_hash", "hash"],
        "cobrança": ["cobranca"],
        "cliente": ["customer", "cliente"],
        "estorno": ["estorno", "refund"],
        "reprocessar": ["reprocessar", "reprocessar"],
        "contas bancárias": ["bank_account", "bank account", "conta bancaria", "bancaria"],
        "antifraude": ["antifraud", "antifraude"],
        "cep": ["zipcode", "cep"]
        }
