# coding: utf8
TAGS = { "magento" : ["magento", "magneto"],
        "opencart" : ["opencart"],
        "prestashop" : ["prestashop"],
        "woocommerce" : ["wordpress, woocommerce"],
        "vtex" : ["vtex"],
        "iset" : ["iset"],
        "betalabs" : ["betalabs", "beta labs"],
        "bis2bis" : ["bis2bis"],
        "ezcommerce" : ["ezcommerce", "ez commerce"],
        "lojaintegrada" : ["lojaintegrada", "loja integrada"],
        "dotstore" : ["dotstore", "dot store"],
        "fitcommerce" : ["fitcommerce", "fit commerce"],
        "signativa" : ["signativa"],
        "flexy" : ["flexy" ],
        "egondola" : ["egondola", "e gondola" ],
        "showare" : ["showare"],
        "edools": ["edools", "e dools", "e-dools"],
        "fbits": ["fbits", "fibits", "f-bits", "fi-bits"],
        "mkxwebsite": ["mkx", "mkxwebsite", "mkx website"],
        "bubb": ["bubb"],
        "e-com.club": ["ecom.club", "e-com.club"],
        "lojcomm": ["lojcomm", "lojconn", "lojcom", "lojcon"],
        "uoou": ["uoou" ],
        "internetAd": ["internetad"],
        "dlojavirtual": ["dlojavirtual", "dloja virtual"],
        "jetcommerce": ["jetcommerce", "jetcomerce", "jet commerce", "jet comerce"],
        "2mind": ["2mind", "2 mind"],
        "bizcommerce": ["bizcommerce", "bizcomerce", "biz commerce", "biz comerce"],
        "php": ["php", "phpv2", "phpv3", "v2", "v3", "php v2", "php v3"],
        "java": ["java"],
        "c#": ["c#", ".net", "aspnet", "vb", "vb.net", "asp.net", "csharp", "visual basic", "visualbasic"],
        "ruby": ["ruby", "rails"],
        "python": ["python", "pithon", "pyton", "piton"],
        "curl": ["curl"],
        "api": ["api"],
        "elasticsearch": ["elasticsearch", "elastic search"], 
        "marketplace": ["marketplace", "market place", "mktplace", "mkt place"],
        "assinatura": ["plans", "plan", "subscription", "subscriptions", "assinatura", "assinaturas", "planos", "plano"],
        "transação": ["transação", "transaction", "transacao"],
        "timeout": ["timeout", "time out"]
        }
